import type { Metadata } from "next";
import { Providers } from "./providers";

import "@/styles/globals.css";
import Link from "next/link";
import { Button } from "@nextui-org/button";
import { AppNavbar } from "@/components/navbar/navbar";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" className="dark">
      <body>
        <AppNavbar />
        <Providers>{children}</Providers>
      </body>
    </html>
  );
}
