import TRPCProvider from '@/server/trpc/trpc-provider'
import '@/styles/_globals.css'
import '@/styles/editor.scss'
import type { Metadata } from 'next'
import { UIProviders } from './providers'

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
  topMenu,
}: {
  children: React.ReactNode
  topMenu: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className="text-smiSans">
        <TRPCProvider>
          <UIProviders>
            {topMenu}
            {children}
          </UIProviders>
        </TRPCProvider>
      </body>
    </html>
  )
}
